version: '3.8'

services:
  mcp-server:
    image: ghcr.io/hudsonclaudino/portainer-mcp:latest
    ports:
      - "8000:8000"
    environment:
      # Substitua pela sua API Key do Portainer
      - PORTAINER_API_KEY=sua_api_key_aqui
      # Substitua pela URL do seu Portainer (Use IP público ou nome de domínio)
      - PORTAINER_URL=http://seu-portainer:9000
    networks:
      - mcp_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  mcp_net:
    driver: overlay
    attachable: true
